### PR TITLE
cleaner code 🥱 

### PR DESCRIPTION
**Pull request by xKiian**

### CODE REVIEW

**Comment by denzelxrt** [comment]
you did jackshit

**Comment by xKiian** [comment]
> you did jackshit
> 

Yea I should've inspired my code from yours.
Like https://github.com/denzelxrt/denzelxrt

My bad buddy

**Review by imvast — CHANGES_REQUESTED** [review]
add new line on file writing and also defer closing it (memory issues)

**Comment by alluding** [comment]
> https://github.com/denzelxrt/denzelxrt

Ironic

**Comment by denzelxrt** [comment]
?

**Comment by alluding** [comment]
> ?

"you did jackshit"

Your code is far from better, unpythonic, and absolutely hideous.

**Comment by alluding** [comment]
> mb "Python enthusiast" didn't know this shit was a competition

Let me know when you stop commenting on a GitHub PR with unrelated and shitty ass remarks, and can actually write good, Pythonic code. 💀

**Comment by denzelxrt** [comment]
you ae the one responding to a 2 month old pr 😭

**Comment by xKiian** [comment]
> you ae the one responding to a 2 month old pr 😭 

I really love your bio <3 

Says everything about you

**Comment by imvast** [comment]
ur all skids 🥱

**Comment by alluding** [comment]
> ur all skids 🥱

Ironic vast.

**Pull request closed without merging**
